### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by egehandulger** [dustinblackman/cordova-ListMusic#2]
Hi @dustinblackman !
I know you no more work on this but I would be really glad if you could help.
I got this plugin working but it puts the output into console. I removed console.log from return row.
`return rootObj;`

However, now it is just returning undefined. Do you have any guesses on how I can put the object into a variable?

Thank you

**Comment by dustinblackman** [comment]
Sorry bud, my java is minimal. This was just a test project to get a feel for Cordova, I haven't explored it much more then then the code base that already exists. :(
